/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.hire.view;

/**
 *
 * @author ASS if
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form Categoryanel
     */
    public CategoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        haderPanel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        bodyPanel3 = new javax.swing.JPanel();
        categoryid3 = new javax.swing.JLabel();
        categoryname3 = new javax.swing.JLabel();
        categoryText3 = new javax.swing.JTextField();
        categoryidText3 = new javax.swing.JTextField();

        title.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        title.setText("Manage Car Category");

        title1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        title1.setText("Manage Car Category");

        javax.swing.GroupLayout haderPanelLayout = new javax.swing.GroupLayout(haderPanel);
        haderPanel.setLayout(haderPanelLayout);
        haderPanelLayout.setHorizontalGroup(
            haderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haderPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        haderPanelLayout.setVerticalGroup(
            haderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        categoryid3.setText("Car Category Id");

        categoryname3.setText("Car Category Name");

        javax.swing.GroupLayout bodyPanel3Layout = new javax.swing.GroupLayout(bodyPanel3);
        bodyPanel3.setLayout(bodyPanel3Layout);
        bodyPanel3Layout.setHorizontalGroup(
            bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryname3)
                    .addComponent(categoryid3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoryText3)
                    .addComponent(categoryidText3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanel3Layout.setVerticalGroup(
            bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanel3Layout.createSequentialGroup()
                        .addGroup(bodyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryid3)
                            .addComponent(categoryidText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(categoryname3)))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(haderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(haderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bodyPanel1;
    private javax.swing.JPanel bodyPanel2;
    private javax.swing.JPanel bodyPanel3;
    private javax.swing.JTextField categoryText;
    private javax.swing.JTextField categoryText1;
    private javax.swing.JTextField categoryText2;
    private javax.swing.JTextField categoryText3;
    private javax.swing.JLabel categoryid;
    private javax.swing.JLabel categoryid1;
    private javax.swing.JLabel categoryid2;
    private javax.swing.JLabel categoryid3;
    private javax.swing.JTextField categoryidText;
    private javax.swing.JTextField categoryidText1;
    private javax.swing.JTextField categoryidText2;
    private javax.swing.JTextField categoryidText3;
    private javax.swing.JLabel categoryname;
    private javax.swing.JLabel categoryname1;
    private javax.swing.JLabel categoryname2;
    private javax.swing.JLabel categoryname3;
    private javax.swing.JPanel haderPanel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
